name: Build Encore Zip

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '.github/scripts/**'
      - 'src/**'
      - 'module/**'
      - 'webui/**'
      - 'gamelist.txt'
      - 'version'

jobs:
  build:
    name: Build Flashable Zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: NDK Setup
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27b
    - name: Build Encore JNI
      working-directory: ./src
      run: ndk-build
    - name: Build WebUI
      working-directory: ./src/webui
      run: |
        npm install
        npm run tailwind
        npm run build
        cp ./dist/* ../../module/webroot
    - name: Compile flashable zip
      id: compileZip
      run: |
        cp -r ./website/docs/public/android-crhome.png ./module/encore_logo.png
        cp -r ./src/libs ./module
        cp -r ./src/scripts/* ./module/system/bin
        cp LICENSE ./module
        bash ./gamelist_compile.sh
        version="$(cat ./version)"
        version_code=$(git rev-list HEAD --count)
        gitsha1=$(git rev-parse --short HEAD)
        sed -i "s/version=.*/version=$version (GIT@$gitsha1)/" ./module/module.prop
        sed -i "s/versionCode=.*/versionCode=$version_code/" ./module/module.prop
        zipName="encore-$version-$version_code_$gitsha1.zip" && echo "zipName=$zipName" >> $GITHUB_OUTPUT
        bash $GITHUB_WORKSPACE/.github/scripts/cr_sha256.sh ./module/system/bin
        bash $GITHUB_WORKSPACE/.github/scripts/cr_sha256.sh ./module/libs
        bash $GITHUB_WORKSPACE/.github/scripts/cr_sha256.sh ./module/META-INF
        bash $GITHUB_WORKSPACE/.github/scripts/cr_sha256.sh ./module/service.sh
        bash $GITHUB_WORKSPACE/.github/scripts/cr_sha256.sh ./module/toast.apk
        bash $GITHUB_WORKSPACE/.github/scripts/cr_sha256.sh ./module/module.prop
        cd ./module && zip -r9 ../$zipName * -x *placeholder* *.map

    - name: Upload Zip as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: encore-zip
        path: ${{ steps.compileZip.outputs.zipName }}
